name: Python Linting
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - "**.py"
      - "Makefile"

jobs:
  python-lint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
      - run: |
          pip install uv
          make fresh-env-only-dev-dependencies
      - name: Add .venv/bin to PATH
        run: echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

      - name: Run MyPy
        run: |
          mypy cider/

      - name: Run ruff
        run: |
          ruff check --exclude "notebooks/" --exclude "synthetic_data/" .

      - name: Check code formatting with Black
        run: |
          cd cider
          black --check .
